//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID_Comment { get; set; }
        public int ID_User { get; set; }
        public string Text { get; set; }
        public int ID_Movie { get; set; }
    
        public virtual Movies Movies { get; set; }
        public virtual Users Users { get; set; }
    }
}
