//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.Comments = new HashSet<Comments>();
            this.Sessions = new HashSet<Sessions>();
        }
    
        public int ID_Movie { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ID_AgeRestriction { get; set; }
        public string Poster { get; set; }
        public string Trailer { get; set; }
        public string Duration { get; set; }
        public string Scriptwriters { get; set; }
        public string Directors { get; set; }
        public string Producers { get; set; }
        public string Actors { get; set; }
        public int ID_Country { get; set; }
        public int ID_Genre1 { get; set; }
        public Nullable<int> ID_Genre2 { get; set; }
        public Nullable<int> ID_Genre3 { get; set; }
    
        public virtual AgeRestrictions AgeRestrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Genres Genres1 { get; set; }
        public virtual Genres Genres2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
