//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public int ID_Session { get; set; }
        public System.DateTime Time { get; set; }
        public int DayTime { get; set; }
        public Nullable<int> ID_Movie { get; set; }
    
        public virtual Movies Movies { get; set; }
    }
}
